# Generated by Django 2.2.6 on 2020-02-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshoot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodieshoots',
            options={'verbose_name_plural': 'FoodieShoots Pics'},
        ),
    ]
