# Generated by Django 2.2.6 on 2020-04-06 15:53

from django.db import migrations, models
import django.utils.timezone
import foodieshoot.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshoot', '0002_auto_20200212_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apks',
            fields=[
                ('apk_version', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('apk_name', models.CharField(max_length=255)),
                ('apk_file', models.FileField(default='foodiesoot.apk', upload_to=foodieshoot.models.upload_location)),
                ('apk_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Apks',
            },
        ),
    ]
