# Generated by Django 2.2.6 on 2020-05-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshoot', '0004_imagedataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodieShoots',
        ),
    ]
